// Generated by https://quicktype.io
export interface User {
    id: string;
    created_at: string;
    email: string;
    uid: null;
    role: 'admin' | 'accountant' | 'superAdmin';
    full_name: string;
}
